### ISSUE TITLE
Offer credentials between UniCore instances

### ISSUE THREAD

**Issue by daniel-mader** [impierce/ssi-agent#109]
### Description

A UniCore instance should be able to offer credentials not only to a wallet (UniMe), but also to another UniCore instance.

The receiving UniCore should have an endpoint open waiting for OID4VCI offers to be posted. It will not immediately accept the offer, but wait for one of it's admin users to accept or decline it.

> ~_All API routes should be prefixed with the current version, such as_ `/v0`.~

Implementation details for the **receiving** side ("holder"):

- ~`POST /holder/offers`~ `GET /openid4vci/offers` (_public_): this is the `credential_offer_endpoint` (as [defined here](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#section-4.1-1)), it accepts a `credential_offer` (by value) or a `credential_offer_uri` (by reference) which should be resolved. It should emit a `CredentialOfferReceived` event.
- `GET /v0/holder/offers`: returns all currently pending offers that show the actual credential to be received if accepted
- `POST /v0/holder/offers/{offer_id}/accept`: accepts the offer, which should trigger actually fetching the credential, `CredentialOfferAccepted` should be emitted
- `POST /v0/holder/offers/{offer_id}/reject`: rejects the offer, removes it from the list, (optional) inform the offering party about the rejection, event of type `CredentialOfferRejected` should be emitted

Implementation details for the **sending** side ("issuer"):

- ~`POST /offers/post`~ `POST /offers/send`: works the same way as the already existing `/offers` endpoint, but issues a `POST` request containing the offer to a target endpoint. Emits an `CredentialOfferSent` event. The required body should look as follows:

```diff
{
-  "openid-credential-offer": "openid-credential-offer://?credential_offer_uri=https%3A%2F%2Fserver%2Eexample%2Ec[...]"
+  "offer_id": "c77feaa4-eb7e-4ed4-bcbf-19358f2e98fb"
  "target_url": "https://example.org/holder/offers"
}
```

The `target_url` can be considered to be shared out-of-band between the two parties.

#### ~Authorization~

~Additionally, the `/holder/offers` endpoint should have some form of access control since it has to be publicly available to fulfill its purpose. Trust lists could be used to only allow verified parties to make offers. A more light-weight approach would be an "offer token" that the **holder** creates beforehand and shares it with the **issuer** out-of-band. The **issuer** has to include the token when it makes the offer. Every token can only be used _once_. This prevents spam and reduces the attack surface. An implementation could look as follows:~

~Implementation details for the **receiving** side ("holder"):~

- ~`POST /holder/offers/new`: creates a new "empty" offer. Should return a generated secure random token string. Only the fields `id` and `token` should be populated. `OfferTokenCreated` should be emitted.~
- ~update `POST /holder/offers` (_public_): should now accept an `application/json` payload that contains: `openid-credential-offer` and `token`. Provided `token` needs to be checked against all current `token`s (created throught the `/new` endpoint). If there's a match, add the `openid-credential-offer` to the offer, else return `401 Unauthorized`. An event `OfferTokenRedeemed` should be emitted. The `token` must now be treated as "burned" and removed from any offer instance (possibly set to `None`). Further calls, even with the same data, should also return a `401 Unauthorized`.~

### Motivation

Allow UniCore to receive credentials for its own identity and fulfill its "holder" role.

### Resources

n/a

**Comment by nanderstabel** [comment]
Reading OID4VCI a bit better we do need to refine it a little since the 'flow' of the Issuer sending the Credential Offer to the Holder is as follows:
1. The issuer obtains the Holder's Client Metadata. This is a OAuth 2.0 concept and it can be retrieved in (at least 2) ways:
    1. Through the [OAuth2.0 Dynamic Client Registration Protocol](https://www.rfc-editor.org/rfc/rfc7591.html). This is the cleanest solution but it will require a lot of implementation work since this is basically just implementing OAuth2.0.
    2. Through obtaining [static Client Metadata](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0-13.html#section-11.1.1-1) out of band. This is obviously very easy and therefore preferred for now.
2. The Client Metadata includes the Holder's `credential_offer_endpoint`
3. The Issuer sends the Credential Offer as a JSON object in a GET request to the `credential_offer_endpoint`. So that means that we need to alter the first endpoint `POST /holder/offers` that you defined a bit:
    1. It must be `GET` instead of `POST`
    2. Since that will interfere with the second endpoint `GET /holder/offers` I suggest we change the first endpoint to something like GET /openid4vci/offers in a similar fashion to our current `/openid4vci/credential` endpoint. We also don't prefix it with `/v0` since it is a spec-defined endpoint.

The rest of the holder API looks good to me!

For the Issuer:
- `POST /offers/post`: We can make this simpler --> after calling the `/v0/offers` endpoint the Credential Offer  (bound to the `offerId`) has already been created in UniCore. So I suggest we change the payload to this:
```
{
  "offer_id": "001",
  "target_url": "https://example.org/openid4vci/offers"
}
````

Perhaps we can also rename this endpoint to `POST /offers/send` since the actual Request that UniCore will send to the target_url will be a GET request, not POST.

Regarding Authorization:
Since the Wallet in OID4VCI (can) act as a OAuth2.0 client, potentially some authorization mechanics are there that would easier cross-over to the authorization concerns that we have for UniCore. That would require some more investigation though.
I will work on Authorization in a separate PR like you suggested
